language: java
sudo: false
install: true

jdk:
  - oraclejdk8

script:
  - mvn verify -B -e -V

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: false

addons:
  apt:
    packages:
      # upgrade java 8 as the default version 1.8.0_31 prevents from compiling sources
      # https://github.com/travis-ci/travis-ci/issues/4042
      - oracle-java8-installer
